issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst # Test data doesn't need to be in constants
        - err113 # Necessary for tests
        - fatcontext # We save contexts for validation

linters-settings:
  nlreturn:
    block-size: 3

  gocritic:
    disabled-checks:
      - "paramTypeCombine"
      - "unnamedResult"
    enabled-tags:
      - "performance"
      - "style"
      - "diagnostic"

  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  enable-all: true
  disable: 
    # Disabled because they're too strict
    - gochecknoglobals # We sometimes use global variables for ease of use
    - depguard # Unnecessary check
    - exhaustruct # We don't always have to fill all fields
    - lll # We don't enforce line lengths
    - wsl # Too strict about statement placement
    - wrapcheck # We don't enforce wrapping
    - varnamelen # We don't enforce var name length
    - testpackage # We don't use test packages
    - funlen # We don't enforce the length of a function
    - exportloopref # Deprecated and no longer required in 1.22

